[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.25.0"
nom = "7.1.3"
rand = "0.8.5"
tinytga = "0.5.0"

[profile.release]
debug = true
